#!/bin/dash
# vim: filetype=sh
#
# http://github.com/mitchweaver/bin
#
# notify on low battery percentage
#

[ $(bperc) = NONE ] && exit

while sleep 60 ; do

	if [ "$(cat /sys/class/power_supply/AC/online)" -eq 0 ]; then
		perc=$(bperc)

		if [ "$perc" -eq 5 ] ; then
			notify-send 'Battery critical!'
		elif [ "$perc" -eq 10 ] ; then
			notify-send -u critical 'Battery low!'
		fi
	fi

done
