#!/bin/mksh
mkfifo /tmp/fifo
dialog --title 'Calculator' --inputbox "" 12 24 2>/tmp/fifo &
input=`cat /tmp/fifo`
output=`echo $input | bc`
dialog --title 'Calculator' --infobox "$output" 12 24
rm /tmp/fifo
