#!/bin/dash
# vim: filetype=sh
#
# still a work in progress

dir=/tmp/pape
file="$(ls -t ~/var/tmp/wall | head -n 1)"

#pape="`date +%Y-%m-%H-%M-%S)`.png"
cp "$dir/$file" ~/papes/

wal --backend colorz -i "~/papes/$file"
rice "~/papes/$file"

[ "$(pgrep bar)" ] &&
    { pkill -9 bar ; nohup bar -- > /dev/null 2>&1 & } &

[ "$(pgrep -x compton)" ] && 
    { pkill -9 compton ; nohup compton -- > /dev/null 2>&1 & } &

