#!/bin/dash

dir=/tmp/pape
file="$dir/$(ls -thAl /tmp/pape | head -n 2 | tail -1 | awk '{print $9 " " $10 " " $11 " " $12 " " $13 " " $14 " " $15}')"

pape="~/papes/$(date)-unsplash-1920x1080.png"

cp $file $pape

wal --backend colorz -i $pape
rice $pape

[ "$(pgrep bar)" ] &&
    { pkill -9 bar ; nohup bar -- > /dev/null 2>&1 & } &

[ "$(pgrep -x compton)" ] && 
    { pkill -9 compton ; nohup compton -- > /dev/null 2>&1 & } &

