#!/bin/dash
# vim: filetype=sh
#
# http://github.com/mitchweaver/bin 
#
# copy commonly used programs to tmpfs
#

/bin/mkdir -p /tmp/bin
/bin/cp -rf /home/hmps/usr/local/bin/* /tmp/bin/
/bin/cp -f /bin/* /tmp/bin/
